apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: ryancraigdavis/farmers_market:kube7
          ports:
            - containerPort: 1359
          env:
            - name: DB_USER
              value: root
            - name: DB_HOST
              value: mysql-cluster-ip-service
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: farmers_market_map
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: dbpass
                  key: DB_PASS
